#!/bin/bash

# Display active Internet connections (only servers)
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
sudo netstat -tuln | grep 'LISTEN'

# Display active UNIX domain sockets (only servers)
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
sudo netstat -xpl | grep 'LISTEN'

