#!/usr/bin/env bash


# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep 4-to_infinity_and_beyond)

# If the process exists, send a termination signal to it
if [ -n "$pid" ]; then
    kill "$pid"
    echo "Terminated"
fi
