#!/bin/bash
# Extract IPv4 addresses using 'ip addr show' command

ipv4_addresses=$(ip addr show | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | grep -vE '^127\.')

# Display the IPv4 addresses
echo "$ipv4_addresses"
